require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-md

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "app/views/**/*"
    - "config/environments/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
